class Roulette:
    
    def __init__(self):
        self.roulette = {
        0: {"color": "green", "type": "single", "symbol": "0", "section": "0"},
        1: {"color": "red", "type": "odd", "symbol": "1", "section": "1-17"},
        2: {"color": "black", "type": "even", "symbol": "2", "section": "1-17"},
        3: {"color": "red", "type": "odd", "symbol": "3", "section": "1-17"},
        4: {"color": "black", "type": "even", "symbol": "4", "section": "1-17"},
        5: {"color": "red", "type": "odd", "symbol": "5", "section": "1-17"},
        6: {"color": "black", "type": "even", "symbol": "6", "section": "1-17"},
        7: {"color": "red", "type": "odd", "symbol": "7", "section": "1-17"},
        8: {"color": "black", "type": "even", "symbol": "8", "section": "1-17"},
        9: {"color": "red", "type": "odd", "symbol": "9", "section": "1-17"},
        10: {"color": "black", "type": "even", "symbol": "10", "section": "1-17"},
        11: {"color": "red", "type": "odd", "symbol": "11", "section": "1-17"},
        12: {"color": "black", "type": "even", "symbol": "12", "section": "1-17"},
        13: {"color": "red", "type": "odd", "symbol": "13", "section": "1-17"},
        14: {"color": "black", "type": "even", "symbol": "14", "section": "1-17"},
        15: {"color": "red", "type": "odd", "symbol": "15", "section": "1-17"},
        16: {"color": "black", "type": "even", "symbol": "16", "section": "1-17"},
        17: {"color": "red", "type": "odd", "symbol": "17", "section": "1-17"},
        18: {"color": "black", "type": "even", "symbol": "18", "section": "18-36"},
        19: {"color": "red", "type": "odd", "symbol": "19", "section": "18-36"},
        20: {"color": "black", "type": "even", "symbol": "20", "section": "18-36"},
        21: {"color": "red", "type": "odd", "symbol": "21", "section": "18-36"},
        22: {"color": "black", "type": "even", "symbol": "22", "section": "18-36"},
        23: {"color": "red", "type": "odd", "symbol": "23", "section": "18-36"},
        24: {"color": "black", "type": "even", "symbol": "24", "section": "18-36"},
        25: {"color": "red", "type": "odd", "symbol": "25", "section": "18-36"},
        26: {"color": "black", "type": "even", "symbol": "26", "section": "18-36"},
        27: {"color": "red", "type": "odd", "symbol": "27", "section": "18-36"},
        28: {"color": "black", "type": "even", "symbol": "28", "section": "18-36"},
        29: {"color": "red", "type": "odd", "symbol": "29", "section": "18-36"},
        30: {"color": "black", "type": "even", "symbol": "30", "section": "18-36"},
        31: {"color": "red", "type": "odd", "symbol": "31", "section": "18-36"},
        32: {"color": "black", "type": "even", "symbol": "32", "section": "18-36"},
        33: {"color": "red", "type": "odd", "symbol": "33", "section": "18-36"},
        34: {"color": "black", "type": "even", "symbol": "34", "section": "18-36"},
        35: {"color": "red", "type": "odd", "symbol": "35", "section": "18-36"},
        36: {"color": "black", "type": "even", "symbol": "36", "section": "18-36"}
    }